name: ktlint format and commit

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  ktlint:
    runs-on: ubuntu-latest

    steps:
      # # Checkout the repository
      # - name: Checkout repository
      #   uses: actions/checkout@v3

      # # Set up Java (ktlint requires Java)
      # - name: Set up JDK 11
      #   uses: actions/setup-java@v3
      #   with:
      #     java-version: '11'

      # # Install ktlint
      # - name: Install ktlint
      #   run: curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.48.0/ktlint && chmod a+x ktlint

      # # Run ktlint format
      # - name: Run ktlint
      #   run: ./ktlint -F "**/*.kt"

      - name: ktlint 
        run: ./gradlew ktlintFormat --parallel

      # Commit changes if any formatting changes were made
      - name: Commit changes if necessary
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          if [[ `git status --porcelain` ]]; then
            git add .
            git commit -m "Apply ktlint format"
            git push
          else
            echo "No formatting changes"
          fi
