name: ktlint format and commit

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  ktlint:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Grant execution permission to gradlew
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Run ktlint format using Gradle
      - name: Run ktlint
        run: ./gradlew ktlintFormat --parallel

      # Commit changes if any formatting changes were made
      - name: Commit changes if necessary
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          if [[ `git status --porcelain` ]]; then
            git add .
            git commit -m "Apply ktlint format"
            git push
          else
            echo "No formatting changes"
          fi
